

**Import** **Libraries**


Data structure which being used when using PyTorch for developing a neural network

Pytorch tensors are similar to numpy arrays, but can also be operated on CUDA-capable Nvidia GPU. Numpy arrays are mainly used in typical machine learning algorithms (such as k-means or Decision Tree in scikit-learn) whereas pytorch tensors are mainly used in deep learning which requires heavy matrix computation [Kaggle]

What is Tensor?
Tensors are containers that can have data in any dimensions. Tensors are the basic data structure in machine learning and deep learning models. A tensor can be considered as a container for numerical data (numbers).
1D Tensor is a vector. 2D Tensor is a Matrix. It can have also 3D like a cube. We can also we can put all these cubes beside each other to have 4D , or even 60D Tensor. And finally it can be ND Tensor.


In [ ]:
import numpy as np
import torch

In [4]:
arr1 = np.array([])
#arr1.dtype
type(arr1)

numpy.ndarray

In [7]:
tens1 = torch.tensor([])
#tens1.dtype
type(tens1)

torch.Tensor

In [10]:
arr2 = np.array([1,2,3,4])
#print(arr2)
type(arr2)

numpy.ndarray

In [12]:
# how make a tensor from an array
tens2 = torch.from_numpy(arr2)
print(tens2)
type(tens2)

NameError: name 'torch' is not defined

In [13]:
# if I change sth in the tensor , dose it change in the array as well? yes
# if you use from_numpy , it uses the same memory as array for the new tensor
tens2[1] = 10
print(tens2)

tensor([ 1, 10,  3,  4])


In [14]:
print(arr2)

[ 1 10  3  4]


In [16]:
# how to prevent changes in the original array? we can use torch.tensor
# in fact it make a copy of the arrey : it creates overhead but avoid changes in the original array
# depends to your application you can use torch.Tensor (computationally moe expensive) or from_array

arr3 = np.array([10,11,12,13])
tens3 = torch.tensor(arr3)
print(tens3)

tensor([10, 11, 12, 13])


In [17]:
tens3[0] = 200
print(tens3)

tensor([200,  11,  12,  13])


In [18]:
print(arr3)

[10 11 12 13]
