**Importing Required Libraries**

Intruduction of Numpy in 'PyTorch for Deep Learning Bootcamp: Zero to Mastery' from Udemy

In [2]:
import numpy as np

**Data Preparation**

In [5]:
#create one dimentional array
NP1 = np.array([1,2,3,4,5,6])
#tpe of array
type(NP1)

numpy.ndarray

In [7]:
# create two dimentional array: for each row I need a []
NP2 = np.array([[1,2,3], [4,5,6]])
NP2
print(NP2.shape)

(2, 3)


In [8]:
print(NP2.size)

6


In [9]:
# see dimention of array
print(NP2.ndim)

2


In [10]:
# the most important part in array is indexing 
NP1[0]

1

In [11]:
# print a range ina array
print(NP1[3:5])

[4 5]


In [15]:
NP2
NP2[0] # give me the first row
NP2[0, 2]
NP2[0][2]

3

In [18]:
NP2[:,0] # all rows , first columns

array([1, 4])

In [19]:
NP2[0,:] # first row. all column :  = NP2[0]

array([1, 2, 3])

In [21]:
NP2[1,1] # secon row, second column

5

In [22]:
NP2[:,:] # all NP2

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
NP2[0:2, 1:3] # all rows 0 and 1, and column second and third column, 3th in the range wont be read
# 0:2 will be read as 0 and 1
# 1:3 will be read as 1 and 2 

array([[2, 3],
       [5, 6]])

In [25]:
NP3 = np.array([[1,2],[3,4]])
NP4 = np.array([[5,6],[7,8]])
print(NP3)
print(NP4)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [26]:
#elementwise summation
NP3 + NP4

array([[ 6,  8],
       [10, 12]])

In [28]:
# elementwise deduction
NP3 - NP4

array([[-4, -4],
       [-4, -4]])

In [29]:
# elementwise division
NP3/ NP4

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [30]:
# elementwise multiplication
NP3 * NP4

array([[ 5, 12],
       [21, 32]])

In [31]:
# matrix format multiplication
NP3 @ NP4

array([[19, 22],
       [43, 50]])